application: vakity-text-analyzer
version: 12
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /
  static_files: about.html
  upload: about\.html    

- url: /about
  static_files: about.html
  upload: about\.html    

- url: /common\.css
  static_files: common.css
  upload: common\.css  

- url: /logo\.png
  static_files: logo.png
  upload: logo\.png  

- url: /analyze
  script: Analyze.app

- url: /path
  script: Path.app

- url: /contact
  script: Contact.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: 2.6
