application: vaktextanalyzer
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
  
- url: /(.*\.html)
  static_files: statics/html/\1
  upload: statics/html(.*\.html)

- url: /images
  static_dir: statics/images

- url: /css
  static_dir: statics/css
  
- url: /Analyze
  script: Analyze.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
